// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1t7fWac_n6eiMxIzCaoFFilZ-fyuhgg0',
    appId: '1:791996836010:web:ef44e6fa8effe73de408d3',
    messagingSenderId: '791996836010',
    projectId: 'bilee-b1058',
    authDomain: 'bilee-b1058.firebaseapp.com',
    storageBucket: 'bilee-b1058.firebasestorage.app',
    measurementId: 'G-G3KLMYX006',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvP-z6aX691GSVOCWt45MmxQV1eyGmkA',
    appId: '1:791996836010:android:70cacfcbbee17b94e408d3',
    messagingSenderId: '791996836010',
    projectId: 'bilee-b1058',
    storageBucket: 'bilee-b1058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUXzYJKeWY7w-Q8GLoJpoO6BlUs7GYlVU',
    appId: '1:791996836010:ios:7e405ab8320e4130e408d3',
    messagingSenderId: '791996836010',
    projectId: 'bilee-b1058',
    storageBucket: 'bilee-b1058.firebasestorage.app',
    iosClientId: '791996836010-bjidfu6ugsps48ena9io4b8ikrcvftml.apps.googleusercontent.com',
    iosBundleId: 'com.example.bilee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUXzYJKeWY7w-Q8GLoJpoO6BlUs7GYlVU',
    appId: '1:791996836010:ios:7e405ab8320e4130e408d3',
    messagingSenderId: '791996836010',
    projectId: 'bilee-b1058',
    storageBucket: 'bilee-b1058.firebasestorage.app',
    iosClientId: '791996836010-bjidfu6ugsps48ena9io4b8ikrcvftml.apps.googleusercontent.com',
    iosBundleId: 'com.example.bilee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1t7fWac_n6eiMxIzCaoFFilZ-fyuhgg0',
    appId: '1:791996836010:web:b95af1d8d6bc5c07e408d3',
    messagingSenderId: '791996836010',
    projectId: 'bilee-b1058',
    authDomain: 'bilee-b1058.firebaseapp.com',
    storageBucket: 'bilee-b1058.firebasestorage.app',
    measurementId: 'G-SWVVQTGYEB',
  );
}
